Remove pytest-runner from setup-requires to fix setup.py on Windows:
It seems that easy install can't install pytest-runner on Windows:

distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pytest-runner')


Former-commit-id: d14b8ab7d23da2607063316e49f33607c5bc0cea